### ISSUE TITLE
pacman-undo script make wrong package names if architecure is "any"

### ISSUE THREAD

**Issue by ssergiienko** [giddie/bits-n-pieces#1]
For cached package `gsettings-desktop-schemas-3.18.1-1-any.pkg.tar.xz`
it output: `gsettings-desktop-schemas-3.18.1-1-x86_64.pkg.tar.xz` and as result it doesn't work

**Comment by giddie** [comment]
Thanks for reporting this. I haven't used this script for a while! I've fixed the issue in 94840533db0dc494220655ed08b9db412c050efc.
