### ISSUE TITLE
Error pacman-undo

### ISSUE THREAD

**Issue by Ste74** [giddie/bits-n-pieces#2]
Hi , i have found your script but when i run this is the output
> stefano@ste74 pacman-undo]$ sh pacman-undo
> pacman-undo: line 19: require: command not found
> pacman-undo: line 20: require: command not found
> pacman-undo: line 22: PACMAN_CONFIG_PATH: command not found
> pacman-undo: line 23: PACMAN_LOG_FILE_PATH: command not found
> pacman-undo: line 24: PACMAN_CACHE_PATH: command not found
> pacman-undo: line 25: PACKAGE_EXTENSION: command not found
> pacman-undo: line 27: syntax error near unexpected token `('
> pacman-undo: line 27: `if not File.exists?(PACMAN_LOG_FILE_PATH)'

**Comment by giddie** [comment]
Hey there! This is a Ruby script, not a shell script. By invoking `sh`, you're forcing it to be run as a shell script, and the syntax is all wrong so it fails. Try it like this:

```
# ./pacman-undo
```

or

```
# ruby pacman-undo
```

**Comment by Ste74** [comment]
My apologies :( i don't realized that .. now work like a charme :)

**Comment by giddie** [comment]
No worries; I'm glad it's useful :)
